version: '3.8'

services:
  # OCR Server Microservice
  ocr-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ocr-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - OCR_API_KEY=${OCR_API_KEY}
      - OCR_API_URL=${OCR_API_URL}
      - FRONTEND_URL=http://localhost:5000
      - LOG_LEVEL=${LOG_LEVEL:-info}
    networks:
      - ocr-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/', (r) => {r.statusCode === 200 ? process.exit(0) : process.exit(1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    volumes:
      - ./server/logs:/app/logs
    labels:
      - "com.ocr.service=backend"
      - "com.ocr.description=OCR processing microservice"

  # Client Application
  ocr-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ocr-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - ocr-server
    networks:
      - ocr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s
    labels:
      - "com.ocr.service=frontend"
      - "com.ocr.description=OCR web client application"

networks:
  ocr-network:
    driver: bridge
    name: ocr-network

volumes:
  server-logs:
    driver: local